services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db-task:/var/lib/postgresql/data
  web:
    image: golang-chi-postgres-api:${IMAGE_VERSION}
    build: .
    ports:
      - "${SRV_ADDR}:${SRV_ADDR}"
    entrypoint: /bin/sh
    command: /start.sh
volumes:
  db-task: